"""SQLAlchemy declarative base with common column conventions.

Provides two base classes for ORM models:

- ``MappedBase``: Minimal declarative base with no columns. Used by models
  that diverge from the standard column pattern (join tables, append-only
  logs, tables with non-standard timestamps).
- ``Base``: Extends ``MappedBase`` with the F001 common column conventions:
  - UUID primary keys generated by PostgreSQL (gen_random_uuid)
  - TIMESTAMPTZ for all temporal columns, stored in UTC
  - created_at is immutable after insert (server default only)
  - updated_at is trigger-managed (server default, updated via DB trigger)

All models MUST inherit from one of these two classes so they share a single
SQLAlchemy ``MetaData`` instance (required for Alembic auto-detection).
"""

import uuid
from datetime import datetime

from sqlalchemy import TIMESTAMP, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class MappedBase(DeclarativeBase):
    """Root declarative base for all ORM models.

    Contains no columns. Models that diverge from the standard column
    pattern (id + created_at + updated_at) inherit directly from this class
    and define their own columns.
    """

    __abstract__ = True


class Base(MappedBase):
    """Abstract base model with common columns for all standard entities.

    All concrete models that follow the standard pattern inherit these columns:
        id: UUID primary key, generated server-side via gen_random_uuid().
        created_at: Immutable creation timestamp, set by server default.
        updated_at: Modification timestamp, set by server default and
            managed by a per-table database trigger (see migrations).
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
