"""SQLAlchemy declarative base with common column conventions.

Implements F001 common column conventions:
- UUID primary keys generated by PostgreSQL (gen_random_uuid)
- TIMESTAMPTZ for all temporal columns, stored in UTC
- created_at is immutable after insert (server default only)
- updated_at is trigger-managed (server default, updated via DB trigger)
"""

import uuid
from datetime import datetime

from sqlalchemy import TIMESTAMP, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Abstract base model with common columns for all entities.

    All concrete models inherit these columns:
        id: UUID primary key, generated server-side via gen_random_uuid().
        created_at: Immutable creation timestamp, set by server default.
        updated_at: Modification timestamp, set by server default and
            managed by a per-table database trigger (see migrations).
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
