"""Protocol and types for token usage tracking.

Defines the ``TokenUsageServiceProtocol`` interface that ``ModelClient``
depends on for recording token consumption, and the ``TokenAttribution``
value object shared across model services.

The concrete implementation (task #57) writes to the ``token_usage_log``
table via SQLAlchemy and satisfies this protocol.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from uuid import UUID

    from tabletop_oracle.models.enums import ModelCapability


@dataclass(frozen=True)
class TokenAttribution:
    """Attribution context for token usage tracking.

    Links a model call to the user, session, message, or document that
    triggered it. ``user_id`` is always required; other fields depend
    on context (session/message for queries, document for ingestion).

    Attributes:
        user_id: UUID of the user who triggered the call.
        session_id: UUID of the game session (None for ingestion).
        message_id: UUID of the message (None for ingestion).
        document_id: UUID of the document (None for queries).
    """

    user_id: UUID
    session_id: UUID | None = None
    message_id: UUID | None = None
    document_id: UUID | None = None


@runtime_checkable
class TokenUsageServiceProtocol(Protocol):
    """Tracks token consumption per model call.

    Writes to the ``token_usage_log`` table (append-only). Called by
    ``ModelClient`` after every successful model invocation.
    """

    async def record(
        self,
        capability: ModelCapability,
        provider: str,
        model_id: str,
        input_tokens: int,
        output_tokens: int,
        attribution: TokenAttribution,
    ) -> None:
        """Record a token usage entry.

        Args:
            capability: Which AI capability the call served.
            provider: Model provider used.
            model_id: Model identifier used.
            input_tokens: Tokens sent to the model.
            output_tokens: Tokens generated by the model.
            attribution: Who/what triggered the call.
        """
        ...
