"""Token usage tracking service.

Records per-call token consumption to the ``token_usage_log`` table and
provides aggregation queries consumed by ``GuardrailService`` for
budget enforcement.

Also defines ``TokenUsageServiceProtocol`` — the interface that
``ModelClient`` depends on for recording token consumption.

All writes are append-only — token usage log entries are never updated
or deleted.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Protocol, runtime_checkable

from sqlalchemy import func, select

from tabletop_oracle.models.enums import MessageType, ModelCapability
from tabletop_oracle.models.message import Message
from tabletop_oracle.models.model_slot import TokenUsageLog

if TYPE_CHECKING:
    from uuid import UUID

    from sqlalchemy.ext.asyncio import AsyncSession


@dataclass(frozen=True)
class TokenAttribution:
    """Attribution context for a model call.

    Links a token usage entry to the user, session, message, or document
    that triggered it. Frozen to prevent accidental mutation after creation.

    Attributes:
        user_id: The user who triggered the call.
        session_id: Session context (None for ingestion).
        message_id: Message context (None for ingestion).
        document_id: Document context (None for queries).
    """

    user_id: UUID
    session_id: UUID | None = None
    message_id: UUID | None = None
    document_id: UUID | None = None


@runtime_checkable
class TokenUsageServiceProtocol(Protocol):
    """Tracks token consumption per model call.

    Writes to the ``token_usage_log`` table (append-only). Called by
    ``ModelClient`` after every successful model invocation.
    """

    async def record(
        self,
        capability: ModelCapability,
        provider: str,
        model_id: str,
        input_tokens: int,
        output_tokens: int,
        attribution: TokenAttribution,
    ) -> None:
        """Record a token usage entry.

        Args:
            capability: Which AI capability the call served.
            provider: Model provider used.
            model_id: Model identifier used.
            input_tokens: Tokens sent to the model.
            output_tokens: Tokens generated by the model.
            attribution: Who/what triggered the call.
        """
        ...


class TokenUsageService:
    """Concrete token usage tracker.

    Writes to the ``token_usage_log`` table (append-only). Called by
    ``ModelClient`` after every successful model invocation.

    Provides aggregation queries used by ``GuardrailService`` to enforce
    per-query, per-session, and daily token budgets.

    Args:
        db: SQLAlchemy async session for database operations.
    """

    def __init__(self, db: AsyncSession) -> None:
        self._db = db

    async def record(
        self,
        capability: ModelCapability,
        provider: str,
        model_id: str,
        input_tokens: int,
        output_tokens: int,
        attribution: TokenAttribution,
    ) -> None:
        """Record a token usage entry.

        Creates an append-only row in ``token_usage_log`` with full
        attribution context. The caller is responsible for committing
        the transaction.

        Args:
            capability: Which AI capability the call served.
            provider: Model provider used (e.g. 'openai', 'anthropic').
            model_id: Provider-specific model identifier.
            input_tokens: Tokens sent to the model.
            output_tokens: Tokens generated by the model.
            attribution: Who/what triggered the call.
        """
        entry = TokenUsageLog(
            capability=capability,
            provider=provider,
            model_id=model_id,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            user_id=attribution.user_id,
            session_id=attribution.session_id,
            message_id=attribution.message_id,
            document_id=attribution.document_id,
        )
        self._db.add(entry)
        await self._db.flush()

    async def get_query_total(
        self,
        session_id: UUID,
        message_id: UUID,
    ) -> int:
        """Get total tokens consumed for a specific query.

        Sums ``input_tokens + output_tokens`` for all log entries
        matching the given message. Used by ``GuardrailService`` for
        per-query token limits.

        Args:
            session_id: The session containing the query (unused in the
                query but kept for API consistency with guardrail context).
            message_id: The message to aggregate tokens for.

        Returns:
            Total token count, or 0 if no entries exist.
        """
        stmt = select(
            func.coalesce(
                func.sum(TokenUsageLog.input_tokens + TokenUsageLog.output_tokens),
                0,
            )
        ).where(TokenUsageLog.message_id == message_id)
        result = await self._db.execute(stmt)
        return int(result.scalar_one())

    async def get_daily_total(self) -> int:
        """Get total tokens consumed today (UTC).

        Sums all token usage from midnight UTC today to now. Used by
        ``GuardrailService`` for daily budget enforcement.

        Returns:
            Total token count for the current UTC day, or 0 if none.
        """
        today_start = datetime.now(UTC).replace(
            hour=0,
            minute=0,
            second=0,
            microsecond=0,
        )
        tomorrow_start = today_start + timedelta(days=1)
        stmt = select(
            func.coalesce(
                func.sum(TokenUsageLog.input_tokens + TokenUsageLog.output_tokens),
                0,
            )
        ).where(
            TokenUsageLog.created_at >= today_start,
            TokenUsageLog.created_at < tomorrow_start,
        )
        result = await self._db.execute(stmt)
        return int(result.scalar_one())

    async def get_session_query_count(self, session_id: UUID) -> int:
        """Get number of user_question messages in a session.

        Counts messages of type ``user_question`` in the given session.
        Used by ``GuardrailService`` for per-session query limits.

        Args:
            session_id: The session to count queries for.

        Returns:
            Number of user_question messages in the session.
        """
        stmt = select(func.count()).where(
            Message.session_id == session_id,
            Message.type == MessageType.USER_QUESTION,
        )
        result = await self._db.execute(stmt)
        return int(result.scalar_one())
