"""Data models and exceptions for the vision processing service.

Contains value objects for vision results, token attribution, and
domain-specific exceptions.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from uuid import UUID


@dataclass(frozen=True)
class ImageDescription:
    """Result of vision processing on an image.

    Attributes:
        text: Text description of the image content.
        confidence: Estimated quality of the description (high/medium/low).
        input_tokens: Number of input tokens consumed by the vision call.
        output_tokens: Number of output tokens generated by the vision call.
    """

    text: str
    confidence: str  # "high", "medium", "low"
    input_tokens: int = 0
    output_tokens: int = 0


@dataclass(frozen=True)
class TokenAttribution:
    """Attribution context for token usage tracking.

    At least one of document_id or session_id should be set. Document-level
    attribution is used during ingestion; session/message-level attribution
    is used during AI workflow queries.

    Attributes:
        user_id: UUID of the user who triggered the call (optional).
        document_id: UUID of the document being processed (optional, ingestion).
        session_id: UUID of the session context (optional, AI workflow).
        message_id: UUID of the message context (optional, AI workflow).
    """

    user_id: UUID | None = None
    document_id: UUID | None = None
    session_id: UUID | None = None
    message_id: UUID | None = None


class VisionProcessingError(Exception):
    """Raised when vision model processing fails after retries.

    Attributes:
        message: Human-readable error description.
        provider: The model provider that failed.
        model_id: The model identifier that failed.
    """

    def __init__(
        self,
        message: str,
        *,
        provider: str = "",
        model_id: str = "",
    ) -> None:
        self.provider = provider
        self.model_id = model_id
        super().__init__(message)


class VisionUnavailableError(Exception):
    """Raised when no vision model slot is configured.

    Used for graceful degradation — callers can catch this to skip
    vision processing when no model is available.
    """

    def __init__(self, message: str = "Vision processing model not configured") -> None:
        super().__init__(message)
